macbook_macos_iterm2_color_schemes_dir: /tmp/mbadolato/iTerm2-Color-Schemes

macbook_domain_custom_dns_domains: []

macbook_homebrew_casks:
  - name: alfred
  - name: alt-tab
  - name: betterdisplay
  - name: chromium
  - name: datagrip
  - name: docker
  - name: firefox
  - name: flameshot
  - name: font-hack
  - name: font-hack-nerd-font
  - name: gimp
  - name: git-credential-manager
  - name: grandperspective
  - name: httpie
  - name: intellij-idea
  - name: iterm2
  - name: keepassxc
  - name: keka
  - name: mattermost
  - name: megasync
  - name: obsidian
  - name: openvpn-connect
  - name: rectangle
  - name: steam
  - name: temurin@17
  - name: thunderbird
  - name: vlc
  - name: vscodium
  - name: yandex-cloud-cli
  - name: zed
  - name: zoom
  - name: thaw

macbook_homebrew_packages:
  - name: ansible-lint
  - name: antidote
  - name: atuin
    description: Shell history manager (sync/backup/search)
    url: https://atuin.sh/
  - name: bat
    url: https://github.com/sharkdp/bat
    description: Modern cat replacement
  - name: git-delta
    description: Git diff pager with syntax highlighting
    url: https://github.com/dandavison/delta
  - name: eza
  - name: fd
  - name: fzf
  - name: glab
  - name: git-crypt
  - name: gpg
  - name: gron
    url: https://github.com/tomnomnom/gron
  - name: hashicorp/tap/terraform
  - name: helm
  - name: htop
  - name: httpie
  - name: jq
  - name: kubectl
  - name: kubectx
  - name: mc
  - name: node
  - name: openconnect
  - name: python
  - name: pwgen
  - name: rg
  - name: telnet
  - name: tldr
  - name: viddy
    description: Modern watch alternative
    url: https://github.com/sachaos/viddy
  - name: zoxide
