---
- name: Packages | install packages
  become: true
  pacman:
    name: "{{ item.name }}"
    state: present
  loop: "{{ installation_packages }}"

- name: Packages | uninstall packages
  become: true
  pacman:
    name: "{{ item.name }}"
    state: absent
  loop:
    - name: vim
      replaced_by: gvim
    - name: top
      replaced_by: htop

- name: Packages | install AUR packages
  become: true
  aur:
    name: "{{ item.name }}"
    state: present
  loop:
    - name: anki-bin
      description: Anki
    - name: fslint
      description: FSlint
      # - name: localepurge
      # description: localepurge
    - name: oxygen-sounds
      description: system sounds for KDE
    - name: hunspell-ru
    - name: yh-bin
      description: yaml syntax highlighter (for zsh kubectl plugin)
    - name: git-credential-manager-core-bin
    # - name: zsh-autocomplete-git
      # source: https://github.com/marlonrichert/zsh-autocomplete

# https://hishtory.dev
- block:
    - name: Packages | Check hiSHtory installed
      command: which hishtory
      register: hishtory_installed
      changed_when: false
    - name: Packages | Install hiSHtory
      shell: curl https://hishtory.dev/install.py | python3 -
      when: hishtory_installed.rc != 0

# vim: set ft=yaml.ansible tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
