---
- name: Provisioning
  hosts: localhost
  gather_facts: true
  tasks:
    - name: MackBook configuration
      ansible.builtin.include_role:
        name: macbook
      when: ansible_facts['os_family'] == 'Darwin'
    - name: Archlinux provisioning
      when: ansible_facts['os_family'] == 'Archlinux'
      block:
        - name: Archlinux installation
          ansible.builtin.include_role:
            name: installation
          tags:
            - installing
        - name: Archlinux configuration
          ansible.builtin.include_role:
            name: configuration
          tags:
            - configuration
        - name: Enable pkgfile db automatic updates
          ansible.builtin.systemd:
            name: pkgfile-update.timer
            state: started
            enabled: true
        - name: Enable TRIM for SSD disk
          ansible.builtin.systemd:
            name: fstrim.timer
            state: started
            enabled: true

# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
