ZDOTDIR=$HOME/.config/zsh

function is_macos() { [[ "$OSTYPE" == darwin* ]] }
function is_linux() { [[ "$OSTYPE" == linux* ]] }

# load local (machine specific) environment variables
if [ -f ~/.zshenv.local ]; then
    source ~/.zshenv.local
fi

export VIEWER="view"
export EDITOR="vim"


export BAT_THEME="Visual Studio Dark+"

export FZF_DEFAULT_COMMAND="fd --type f --color=never --hidden --exclude .git"
export FZF_ALT_C_COMMAND="fd --type d . --color=never --hidden --exclude .git"

# add support for Ctrl+O to open selected file in Vim
export FZF_DEFAULT_OPTS="--bind='ctrl-o:execute(vim {} < /dev/tty > /dev/tty)'"

if is_macos; then
    # https://support.azul.com/hc/en-us/articles/17535521715476-Setting-the-default-Java-version-on-macOS
    export JAVA_VERSION=17
else
    export SYSTEMD_EDITOR=$EDITOR
fi
