export PATH="${PATH}:${HOME}/.krew/bin"

if is_macos; then
    # Shell history file path
    export HISTFILE=$HOME/.zsh_history
    source $HOMEBREW_PREFIX/opt/antidote/share/antidote/antidote.zsh
    OS=macos
else
    export HISTFILE=$HOME/.cache/.zsh_history
    # TODO load antidote
    OS=archlinux
fi
# ZSH_THEME="robbyrussell"
# ZSH_THEME="fwalch"
ZSH_THEME="Chill/chill"

# Number of commands to save in history
export SAVEHIST=100000

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Command execution timestamp shown in the history command output
HIST_STAMPS="%T %d.%m.%y"

zstyle ':antidote:bundle' use-friendly-names 'yes'
# Load OMZ plugins
antidote load ${ZDOTDIR:-$HOME}/ohmyzsh.zsh_plugins.txt
# Directory for custom scripts/plugins/themes
ZSH_CUSTOM=$HOME/.zsh-custom




ZSH=$(antidote path ohmyzsh/ohmyzsh)
source $ZSH/oh-my-zsh.sh

PROMPT_THEME=pure
# PROMPT_THEME=spaceship

# Load common plugins
antidote load ${ZDOTDIR:-$HOME}/.zsh_plugins.txt
autoload -Uz promptinit && promptinit && prompt $PROMPT_THEME

# Begin Atuin
# The same does Atuin zsh plugin
# https://github.com/atuinsh/atuin/blob/main/atuin.plugin.zsh
# There is no point to clone whole repository just for 5 lines
FOUND_ATUIN=$+commands[atuin]

if [[ $FOUND_ATUIN -eq 1 ]]; then
  source <(atuin init zsh --disable-up-arrow)
fi
# End Atuin

# function fzf_open_in_vim() {
    # vim $(fzf)
# }

# zle -N fzf_open_in_vim
# bindkey '^[o' fzf_open_in_vim
# bindkey '^[o' 'vim $(fzf)'

# Search a file with fzf and then open it in an editor
function fzf_open_in_editor() {
  echo $FZF_DEFAULT_COMMAND
  local file="$(fzf)"
  # Open the file if it exists
  if [ -n "$file" ]; then
    # Use the default editor if it's defined, otherwise Vim
    ${EDITOR:-vim} "$file"
  fi
}

# zle -N fzf_open_in_editor
# bindkey '^[o' fzf_open_in_editor
alias o="fzf_open_in_editor"

#============= fubectl =============#
# https://github.com/kubermatic/fubectl

unalias ked
unalias kdel
eval "$(zoxide init --cmd j zsh)" # Zoxide configuration

# Enable zsh-autocomplete plugin
# source /usr/share/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/mcli mcli

# Begin yc
# Enable shell command completion
if is_macos; then
    local yc_version="$(yc --version | awk '{print $4}')"
    source "$HOMEBREW_PREFIX/Caskroom/yandex-cloud-cli/$yc_version/yandex-cloud-cli/completion.zsh.inc"
else
    if [ -f "$HOME/yandex-cloud/completion.zsh.inc" ]; then
    source "$HOME/yandex-cloud/completion.zsh.inc"; fi
fi
# End yc
